server:
  port: 8001

spring:
  application:
    name: primo-register
  datasource:
    url: jdbc:postgresql://localhost:5432/armory
    username: primo
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
