version: "3.8"
services:
  primo-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/postgres
      - POSTGRES_USER=primo
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=armory
    restart: unless-stopped