server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: primo
    password: password
    exchange: message_exchange
    routingKey: message_routing_key
    queue: message_queue

management:
  tracing:
    sampling:
      probability: 1.0

