server:
  port: 8003

spring:
  cloud:
    gateway:
      routes:
        - id: primo-payment
          uri: lb://primo-payment
          predicates:
            - Path=/payment/**
        - id: primo-email-sender
          uri: lb://primo-email-sender
          predicates:
            - Path=/email/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0