spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: primo
    password: password
    exchange: message_exchange
    routingKey: message_routing_key
    queue: message_queue

server:
  port: 8001